### ISSUE TITLE
Excuse me, Scatter has been developed for so long. Is there any plan to make a mobile version?

### ISSUE THREAD

**Issue by cppfuns** [GetScatter/ScatterDesktop#513] opened 2020-06-11 09:34 UTC

**Comment by Soleone** [comment] 2020-08-10 04:59
Duplicate of https://github.com/GetScatter/ScatterDesktop/issues/519

Could you close this one please to help keep the list of issues focused? Thanks!

**Closed as completed** 2020-08-11 02:49 UTC
